syntax = "proto3";

package Api;

enum EAction {
  DELETE = 0;
  SET = 1;
}

message TPosition {
  repeated float vector = 1;
}

message TVelocity {
  repeated float vector = 1;
}

message TRotation {
  repeated float vector = 1;
}

message TPing {
  int64 timestamp = 1;
  int32 ping_id = 2;
  int32 total_online = 3;
}

message TAnimation {
  string name = 1;
  float speed = 2;
  bool playing = 3;
}

message TClientState {
  int32 world_hash = 1;
  TPosition position = 2;
  TVelocity velocity = 3;
  TRotation rotation = 4;
  TAnimation animation = 5;
  TVisibility visibility = 6;
}

message TSignedClientState {
  TClientState state = 1;
  EAction action = 2;

  // server only
  uint32 uid = 3;
  string name = 4;
}

message TSignedClientMessage {
  uint32 uid = 1;
  string msg = 2;
}

message TVisibility {
  repeated string shown = 1;
  repeated string hidden = 2;
}

message TClientData {
  string name = 1;
  oneof payload {
    TSignedClientMessage chat_message = 2;
    TPing ping = 3;
    TSignedClientState signed_state = 4;
    bool sync_request = 5;
  }
}

/////////////////
// Server part //
/////////////////

message TPlayersState {
  repeated TSignedClientState signed_state = 1;
  int32 your_uid = 2;
}

message TServerData {
  oneof payload {
    TPlayersState players = 1;
    TSignedClientMessage chat_message = 2;
    bool state_request = 3;
    TPing ping = 4;
  }
}
